kabuku/makerfaire-tokyo-2018

package-lock.json
package.json
tsconfig.json
web/index.html
web/index.ts

クライアントの初期実装です。
ほぼ下記のサンプルのままです。
https://github.com/tensorflow/tfjs-examples/tree/master/webcam-transfer-learning

Setup web client

---

.gitignore
README.md
mqtt/mosquitto/config/mosquitto.conf
package.json
web/robot.ts

feat: enable use Navigator.getUserMedia

---

web/index.ts

- "Stop" ボタンを押したらロボットが停止するように"0"を送信するように変更
- ロボットに命令を毎秒送信するように変更
This resolves #11

Improve control

---

web/index.html
web/index.ts

とりあえず[こちら](https://github.com/kabuku/makerfaire-tokyo-2018/issues/26#issuecomment-400914733)をレイアウトしました。

style: layout whole things

---

web/index.ts
web/keyEventHandler.ts

↑で 1、↓で -1、 space で 0 を送るようにしました。
0 が space なのは YouTube などの動画配信サイトで space を押すと再生・停止が制御できるのとイメージ的に揃えました。

feat: enable controlling by key (#32)

---

web/camera.ts
web/index.html
web/index.ts

feat: enable selecting cameras

---

web/index.ts
web/keyEventHandler.ts

一つのページで左右両方ともキーボードで操作したいという要望があったため対応しました。

feat: enable controlling both wheels with keyboard in a single page

---

robot/raspberrypi_client/mqtt_client.py

Raspberry Piでも動くプラグラムを作成しました。ついでにLEDも光らせるようにしました。
レビューをよろしくおねがいします。
Closes #28

Raspberry Piで動かす

---

web/classifier.ts
web/index.html
web/index.ts
web/pairplay.css
web/pairplay.html
web/pairplay.ts
web/styles.css

stop ボタンを押した後、それまでの学習済みモデルを使って再度 start できるようにしました。
修正にあたり、これまで `pairplay.ts` からしか使われていなかった `Classifier` を `index.ts` からも使うようにしたため、少し差分が大きくなっています。

feat: preserve learned data on stop

---

.gitignore
README.md
package-lock.json
package.json
scripts/loadMobilenet.js
web/helper.ts

Mobilenet のモデルをローカルに保存することで、実行時はインターネットに繋がらなくても動かせるようにしました。

feat: serve Mobilenet model from localhost

---

web/index.ts
web/oneside.css
web/pairplay.css
web/pairplay.ts
web/styles.css

顔を予測している時、無駄にボーダーが点滅するアニメーションをいれてみました。

Blink animation

---

web/classifier.ts
web/index.ts
web/pairplay.ts

選択クロップ機能の追加 (#66) に際して，Canvas画像を扱いたいため，`Classifier` クラスを一部変更します。

分類器クラスとカメラの情報とを分離する

---

web/camera.ts
web/index.html
web/index.ts
web/oneside.css
web/pairplay.css
web/pairplay.html
web/pairplay.ts
web/squareCrop.ts

選択クロップ機能を実装しました。雑ですが、デモには困らないはずです。

Square cropped capture

---

web/pairplay.html
web/pairplay.ts
web/robot.ts

ロボット名を select で選択できるようにしました
fixes #68

feat: make robot name selectable

---

web/classifier.ts
web/index.ts
web/pairplay.html
web/pairplay.ts

Fixes #65 
前進、停止だけのイージーモードを作りました。
#75 の差分が混ざっているのでご注意ください。

feat: implement easy mode

---

web/index.html
web/pairplay.css
web/pairplay.ts
web/styles.css

画面を白くしました。色のチョイスはテキトーです。 (一応、黒い画面に切り替えられるようになっています。)
Fix #67 
「タタカイノキロク」の部分は、後でちゃんとCSSをあてたいので現段階ではそのままになっています。

テーマの切り替え。(画面を白くする)

---

web/index.html
web/keyEventHandler.ts
web/pairplay.ts
web/styles.css
web/velocityTuner.ts

ロボット側で subscribe した値に応じて速度調整が可能とのことなので、ブラウザから任意の速度を送信できるようにしました。
調整用の UI を雑に左上に配置しています。
とりあえず↑の値をデフォルトにしています。
`localStorage` を使っており、ロボットごとに設定した値が記憶されます。

feat: velocity tuning

---

web/camera.ts
web/index.html
web/pairplay.css
web/pairplay.ts

feat: show captured image on the corresponding button

---

web/imageRecorder.ts
web/singleplay.ts

fix: compilation errors

---

web/pairplay.ts

二人同時でサンプリングできるようにしました。
実装としてはやややっつけ感があります…

feat: parallel sampling

---

web/imageRecorder.ts
web/server.ts
web/singleplay.css
web/singleplay.html
web/singleplay.ts
web/velocityTuner.ts

一人でロボット一台を操作できる画面です。前進、旋回、後退の3つの顔で操作出来ます。ついでに #98 の変更をパクって入れさせてもらいました。

Single play mode
